blueprint:
  name: ToD Scene Script
  description: Set room scene based on the time of day. Set to bright if activated when lights are already on.
  domain: script
  input:
    script_alias:
      description: The alias for the script
    script_icon:
      description: The icon to use for the script
    light_group:
      description: The group of lights to set the scene for
    dawn_scene:
      description: The scene to use at first light
    sunrise_scene:
      description: The scene to use just after sunrise
    bright_scene:
      description: The scene to use during the day (or when activated when lights are already on)
    sunset_scene:
      description: The scene to use between sunset and midnight
    night_scene:
      description: The scene to use between midnight and first light
alias: !input script_alias
sequence:
  - choose:
      - conditions:
          - condition: and
            conditions:
              - condition: sun
                after: sunrise
                after_offset: "-01:00:00"
              - condition: sun
                before: sunrise
              - condition: state
                entity_id: !input light_group
                state: "off"
        sequence:
          - service: scene.turn_on
            target:
              entity_id: !input dawn_scene
            metadata: {}
      - conditions:
          - condition: and
            conditions:
              - condition: sun
                after: sunrise
              - condition: sun
                before: sunrise
                before_offset: "+01:00:00"
              - condition: state
                entity_id: !input light_group
                state: "off"
        sequence:
          - service: scene.turn_on
            target:
              entity_id: !input sunrise_scene
            metadata: {}
      - conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id: !input light_group
                state: "on"
              - condition: and
                conditions:
                  - condition: sun
                    after: sunrise
                    after_offset: "+01:00:00"
                  - condition: sun
                    before: sunset
                  - condition: state
                    entity_id: !input light_group
                    state: "off"
        sequence:
          - service: scene.turn_on
            target:
              entity_id: !input bright_scene
            metadata: {}
      - conditions:
          - condition: and
            conditions:
              - condition: sun
                after: sunset
              - condition: state
                entity_id: !input light_group
                state: "off"
        sequence:
          - service: scene.turn_on
            target:
              entity_id: !input sunset_scene
            metadata: {}
      - conditions:
          - condition: and
            conditions:
              - condition: sun
                before: sunrise
              - condition: state
                entity_id: !input light_group
                state: "off"
        sequence:
          - service: scene.turn_on
            target:
              entity_id: !input night_scene
            metadata: {}
mode: single
icon: !input script_icon
